build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: DEVIreg2MQTT add-on"
  org.opencontainers.image.description: "Home Assistant addon for DEVIreg Smart thermostats over MQTT"
  org.opencontainers.image.source: "https://github.com/Swiftwork/hassio-devireg2mqtt"
  org.opencontainers.image.licenses: "MIT"