build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: DEVIreg2MQTT add-on"
  org.opencontainers.image.description: Home Assistant addon for DEVIreg Smart thermostats over MQTT
  org.opencontainers.image.source: https://github.com/Swiftwork/hassio-devireg2mqtt
  org.opencontainers.image.licenses: MIT