name: DEVIreg2MQTT
version: 1.0.6
description: Home Assistant addon for DEVIreg Smart thermostats over MQTT
slug: devireg2mqtt
url: https://github.com/Swiftwork/hassio-devireg2mqtt/tree/main/devireg2mqtt
init: false
timeout: 30
services:
  - mqtt:need
panel_icon: mdi:thermostat
panel_title: DEVIreg
arch:
  - aarch64
  - amd64
options:
  mqtt:
    host: mqtt://core-mosquitto
    port: 1883
    user: mqtt
    password: null
  devi:
    peerId: null
    privateKey: null
    houseName: Home
    userName: null
  devi_rooms:
    - serialNumber: null
      devicePeerID: null
      name: null
schema:
  mqtt:
    host: str
    port: port
    user: str
    password: password
  devi:
    peerId: str
    privateKey: password
    houseName: str
    userName: str
  devi_rooms:
    - serialNumber: str
      devicePeerID: str
      name: str
image: ghcr.io/home-assistant/{arch}-hassio-devireg2mqtt